---
version: '^0.7.0-dev'
build:
  - !repo
      path: ~/dotfiles
      url: https://github.com/jcthomassie/dotfiles.git
  - !repo
      path: ~/yurt
      url: https://github.com/jcthomassie/yurt.git

  # OS specifics:
  - !case
    - condition: !any
        - !locale { distro: ubuntu }
        - !locale { distro: debian }
      include:
        - !require [ apt, apt-get ]
    - condition: !locale { platform: bsd }
      include:
          - !require [ pkg ]
    - condition: !locale { platform: windows }
      include:
        - !require [ choco ]
    - condition: !default
      include:
        - !require [ brew ]

  - !case
    # Ubuntu only
    - condition: !locale { distro: ubuntu }
      include:
        - !install
          - name: build-essential
          - name: libffi-dev
          - name: libssl-dev
          - name: pkg-config

  # Platform specifics
  - !case
    # Windows only
    - condition: !locale { platform: windows }
      include:
        - !link
          - target: ${{ repo#dotfiles.path }}/pwsh/profile.ps1
            source: ~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1
          - target: ${{ repo#dotfiles.path }}/nvim
            source: ${{ env:LocalAppData }}/nvim
          - target: ${{ repo#dotfiles.path }}/.wt.json
            source: ${{ env:LocalAppData }}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
          - target: ${{ repo#dotfiles.path }}/python/.flake8
            source: ~/.flake8
          - target: ${{ repo#dotfiles.path }}/python/.mypy.ini
            source: ~/.mypy.ini
          - target: ${{ repo#dotfiles.path }}/git/.gitconfig.os.win
            source: ~/.gitconfig.os
    # Posix only
    - condition: !default
      include:
        - !install
          - name: zsh
          - name: exa
          - name: grep
          - name: curl
        - !link
          - target: ${{ repo#dotfiles.path }}/zsh/.zshenv
            source: ~/.zshenv
          - target: ${{ repo#dotfiles.path }}/nvim
            source: ~/.config/nvim
          - target: ${{ repo#dotfiles.path }}/python/.flake8
            source: ~/.config/flake8
          - target: ${{ repo#dotfiles.path }}/python/.mypy.ini
            source: ~/.config/.mypy.ini
          - target: ${{ repo#dotfiles.path }}/git/.gitconfig.os.posix
            source: ~/.gitconfig.os
          - target: ${{ repo#dotfiles.path }}/kitty
            source: ~/.config/kitty

  # Install rust toolchain
  - !require [ cargo ]
  - !install
    - name: cargo-edit
      managers: [ cargo ]

  # Install essential packages
  - !install
    - name: git
    - name: bat
    - name: nvim
    - name: gh
    - name: zoxide
    - name: ripgrep
    - name: delta
      aliases: { brew: git-delta, cargo: git-delta }
    - name: pyenv
      aliases: { choco: pyenv-win }
      managers: [ brew, choco ]

  # Apply symlinks
  - !link
    - target: ${{ repo#dotfiles.path }}/git/.gitconfig
      source: ~/.gitconfig
    - target: ${{ repo#dotfiles.path }}/git/.gitignore_global
      source: ~/.gitignore_global
    - target: ${{ repo#dotfiles.path }}/python/.isort.cfg
      source: ~/.isort.cfg
    - target: ${{ repo#dotfiles.path }}/ssh/.ssh_config
      source: ~/.ssh/config

  # User specific configs
  - !case
    - condition: !locale { user: julianth }
      include:
        - !link
          - target: ${{ repo#dotfiles.path }}/git/.gitconfig.user.julianth
            source: ~/.gitconfig.user
          - target: ${{ repo#dotfiles.path }}/ssh/.ssh_config.user.julianth
            source: ~/.ssh/config.user
    - condition: !default
      include:
        - !link
          - target: ${{ repo#dotfiles.path }}/git/.gitconfig.user.default
            source: ~/.gitconfig.user
          - target: ${{ repo#dotfiles.path }}/ssh/.ssh_config.user.default
            source: ~/.ssh/config.user
