---
version: 0.2.0

repo:
  local: ~/dotfiles
  remote: https://github.com/jcthomassie/dotfiles.git

shell: zsh

build:
  - case:
    - positive:
        spec: { distro: ubuntu }
        include:
          - install:
            - name: build-essential
              managers: [ apt ]
    # Windows only
    - positive:
        spec: { platform: windows }
        include:
          - bootstrap: [ choco ]
          - link:
            - tail: $YURT_REPO_LOCAL/pwsh/profile.ps1
              head: ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1
            - tail: $YURT_REPO_LOCAL/.wt.json
              head: $LocalAppData/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
            - tail: $YURT_REPO_LOCAL/python/.flake8
              head: ~/.flake8
    # Posix only
    - negative:
        spec: { platform: windows }
        include:
          - bootstrap: [ brew ]
          - install:
            - name: zsh
              managers: [ brew, apt-get ]
            - name: exa
              managers: [ brew, apt, cargo ]
          - link:
            - tail: $YURT_REPO_LOCAL/zsh/.zshenv
              head: ~/.zshenv
            - tail: $YURT_REPO_LOCAL/python/.flake8
              head: ~/.config/flake8

  # Bootstrap package managers
  - bootstrap: [ cargo ]

  # Install essential packages
  - install:
    - name: git
      managers: [ brew, choco ]
    - name: delta
      alias: git-delta
      managers: [ brew, cargo, choco ]
    - name: bat
      managers: [ brew, choco, cargo, apt ]
    - name: vim
      managers: [ brew, choco ]
    - name: gh
      managers: [ brew, choco ]
    - name: zoxide
      managers: [ brew, choco ]

  # Apply symlinks
  - link:
    - tail: $YURT_REPO_LOCAL/git/.gitconfig
      head: ~/.gitconfig
    - tail: $YURT_REPO_LOCAL/git/.gitignore_global
      head: ~/.gitignore_global
    - tail: $YURT_REPO_LOCAL/.vimrc
      head: ~/.vimrc
    - tail: $YURT_REPO_LOCAL/python/.mypy.ini
      head: ~/.mypy.ini
    - tail: $YURT_REPO_LOCAL/python/.isort.cfg
      head: ~/.isort.cfg

  # Amazon specifics
  - case:
    - positive:
        spec: { user: thomajl }
        include:
          - link:
            - tail: $YURT_REPO_LOCAL/git/.gitconfig.local##user.thomajl
              head: ~/.gitconfig.local
    - default:
        include:
          - link:
            - tail: $YURT_REPO_LOCAL/git/.gitconfig.local##default
              head: ~/.gitconfig.local
