---
repo:
  local: ~/dotfiles
  remote: https://github.com/jcthomassie/dotfiles.git

build:
  # Install ubuntu build requirements
  - case:
    - local:
        spec:
          distro: ubuntu
        build:
          - install:
            - name: build-essentials
              managers:
              - apt

  # Bootstrap package managers
  - case:
    - local:
        spec:
          platform: windows
        build:
          - bootstrap:
            - choco
    - default:
        build:
          - bootstrap:
            - brew

  - bootstrap:
    - cargo

  # Install essential packages
  - install:
    - name: zsh
      managers:
      - brew
      - apt-get
    - name: git
      managers:
      - brew
      - apt
      - choco
    - name: git-delta
      alias: delta
      managers:
      - brew
      - cargo
      - choco
    - name: bat
      managers:
      - brew
      - choco
      - cargo
      - apt
    - name: vim
      managers:
      - brew
      - choco
    - name: exa
      managers:
      - brew
      - apt
      - cargo
    - name: gh
      managers:
      - brew
      - choco

  # Apply symlinks
  - link:
    - tail: $YURT_REPO_LOCAL/.zsh/.zshenv
      head: ~/.zshenv
    - tail: $YURT_REPO_LOCAL/.gitconfig
      head: ~/.gitconfig
    - tail: $YURT_REPO_LOCAL/.gitignore_global
      head: ~/.gitignore_global
    - tail: $YURT_REPO_LOCAL/.vimrc
      head: ~/.vimrc

  # Local gitconfig
  - case:
    - local:
        spec:
          user: thomajl
        build:
          - link:
            - tail: $YURT_REPO_LOCAL/.gitconfig.local##user.thomajl
              head: ~/.gitconfig.local

    - default:
        build:
          - link:
            - tail: $YURT_REPO_LOCAL/.gitconfig.local##default
              head: ~/.gitconfig.local
