---
version: 0.4.0
build:
  - repo:
      path: ~/dotfiles
      url: https://github.com/jcthomassie/dotfiles.git
  - repo:
      path: ~/yurt
      url: https://github.com/jcthomassie/yurt.git

  # OS specifics
  - case:
    # Ubuntu only
    - positive:
        condition: { distro: ubuntu }
        include:
          - require: [ apt, apt-get ]
          - install:
            - name: build-essential
            - name: libssl-dev
            - name: pkg-config
  - case:
    # Windows only
    - positive:
        condition: { platform: windows }
        include:
          - require: [ choco ]
          - link:
            - tail: ${{ dotfiles.path }}/pwsh/profile.ps1
              head: ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1
            - tail: ${{ dotfiles.path }}/nvim
              head: ~/AppData/Local/nvim
            - tail: ${{ dotfiles.path }}/.wt.json
              head: ${{ env.LocalAppData }}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
            - tail: ${{ dotfiles.path }}/python/.flake8
              head: ~/.flake8
            - tail: ${{ dotfiles.path }}/git/.gitconfig.os.win
              head: ~/.gitconfig.os
    # Posix only
    - default:
        include:
          - require: [ brew ]
          - run: brew bundle --file ${{ dotfiles.path }}/.brewfile
          - install:
            - name: zsh
            - name: exa
          - link:
            - tail: ${{ dotfiles.path }}/zsh/.zshenv
              head: ~/.zshenv
            - tail: ${{ dotfiles.path }}/nvim
              head: ~/.config/nvim
            - tail: ${{ dotfiles.path }}/python/.flake8
              head: ~/.config/flake8
            - tail: ${{ dotfiles.path }}/git/.gitconfig.os.posix
              head: ~/.gitconfig.os

  # Install rust toolchain
  - require: [ cargo ]
  - install:
    - name: cargo-edit
      managers: [ cargo ]

  # Install essential packages
  - install:
    - name: git
    - name: bat
    - name: nvim
    - name: gh
    - name: zoxide
    - name: ripgrep
    - name: delta
      aliases: { brew: git-delta, cargo: git-delta }

  # Apply symlinks
  - matrix:
      values:
        tail:
          - git/.gitconfig
          - git/.gitignore_global
          - python/.mypy.ini
          - python/.isort.cfg
        head:
          - ~/.gitconfig
          - ~/.gitignore_global
          - ~/.mypy.ini
          - ~/.isort.cfg
      include:
        - link:
          - tail: ${{ dotfiles.path }}/${{ matrix.tail }}
            head: ${{ matrix.head }}

  # User specific configs
  - case:
    - positive:
        condition: { user: thomajl }
        include:
          - link:
            - tail: ${{ dotfiles.path }}/git/.gitconfig.user.amazon
              head: ~/.gitconfig.user
    - default:
        include:
          - link:
            - tail: ${{ dotfiles.path }}/git/.gitconfig.user.default
              head: ~/.gitconfig.user
            - tail: ${{ dotfiles.path }}/ssh/.ssh_config
              head: ~/.ssh/config
