---
version: 0.2.0

shell: zsh

build:
  - repo:
      name: dotfiles
      local: ~/dotfiles
      remote: https://github.com/jcthomassie/dotfiles.git
  - case:
    - positive:
        spec: { distro: ubuntu }
        include:
          - require: [ apt, apt-get ]
          - matrix:
              values:
                package: [ build-essential, libssl-dev, pkg-config ]
              include:
                - install:
                  - name: ${{ matrix.package }}
                    managers: [ apt ]
    # Windows only
    - positive:
        spec: { platform: windows }
        include:
          - require: [ choco ]
          - link:
            - tail: ${{ dotfiles.local }}/pwsh/profile.ps1
              head: ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1
            - tail: ${{ dotfiles.local }}/.wt.json
              head: ${{ env.LocalAppData }}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
            - tail: ${{ dotfiles.local }}/python/.flake8
              head: ~/.flake8
    # Posix only
    - negative:
        spec: { platform: windows }
        include:
          - require: [ brew ]
          - run: brew bundle --file ${{ dotfiles.local }}/.brewfile
          - install:
            - name: zsh
            - name: exa
          - link:
            - tail: ${{ dotfiles.local }}/zsh/.zshenv
              head: ~/.zshenv
            - tail: ${{ dotfiles.local }}/python/.flake8
              head: ~/.config/flake8

  # Bootstrap package managers
  - require: [ cargo ]

  # Install essential packages
  - install:
    - name: git
    - name: delta
      aliases: { brew: git-delta, cargo: git-delta }
    - name: bat
    - name: vim
    - name: gh
    - name: zoxide

  # Apply symlinks
  - matrix:
      values:
        tail:
          - .vimrc
          - git/.gitconfig
          - git/.gitignore_global
          - python/.mypy.ini
          - python/.isort.cfg
        head:
          - ~/.vimrc
          - ~/.gitconfig
          - ~/.gitignore_global
          - ~/.mypy.ini
          - ~/.isort.cfg
      include:
        - link:
          - tail: ${{ dotfiles.local }}/${{ matrix.tail }}
            head: ${{ matrix.head }}

  # Amazon specifics
  - case:
    - positive:
        spec: { user: thomajl }
        include:
          - link:
            - tail: ${{ dotfiles.local }}/git/.gitconfig.local##user.thomajl
              head: ~/.gitconfig.local
    - default:
        include:
          - link:
            - tail: ${{ dotfiles.local }}/git/.gitconfig.local##default
              head: ~/.gitconfig.local
