---
version: '>=0.6.0'
build:
  - !repo
      path: ~/dotfiles
      url: https://github.com/jcthomassie/dotfiles.git
  - !repo
      path: ~/yurt
      url: https://github.com/jcthomassie/yurt.git

  # OS specifics:
  - !case
    - condition: !any
        - !locale { distro: ubuntu }
        - !locale { distro: debian }
      include:
        - !require [ apt, apt-get ]
    - condition: !locale { platform: bsd }
      include:
          - !require [ pkg ]
    - condition: !locale { platform: windows }
      include:
        - !require [ choco ]
    - include:
        - !require [ brew ]

  - !case
    # Ubuntu only
    - condition: !locale { distro: ubuntu }
      include:
        - !install
          - name: build-essential
          - name: libffi-dev
          - name: libssl-dev
          - name: pkg-config

  # Platform specifics
  - !case
    # Windows only
    - condition: !locale { platform: windows }
      include:
        - !link
          - tail: ${{ dotfiles.path }}/pwsh/profile.ps1
            head: ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1
          - tail: ${{ dotfiles.path }}/nvim
            head: ${{ env.LocalAppData }}/nvim
          - tail: ${{ dotfiles.path }}/.wt.json
            head: ${{ env.LocalAppData }}/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
          - tail: ${{ dotfiles.path }}/python/.flake8
            head: ~/.flake8
          - tail: ${{ dotfiles.path }}/python/.mypy.ini
            head: ~/.mypy.ini
          - tail: ${{ dotfiles.path }}/git/.gitconfig.os.win
            head: ~/.gitconfig.os
    # Posix only
    - include:
        - !install
          - name: zsh
          - name: exa
          - name: grep
          - name: curl
        - !link
          - tail: ${{ dotfiles.path }}/zsh/.zshenv
            head: ~/.zshenv
          - tail: ${{ dotfiles.path }}/nvim
            head: ~/.config/nvim
          - tail: ${{ dotfiles.path }}/python/.flake8
            head: ~/.config/flake8
          - tail: ${{ dotfiles.path }}/python/.mypy.ini
            head: ~/.config/.mypy.ini
          - tail: ${{ dotfiles.path }}/git/.gitconfig.os.posix
            head: ~/.gitconfig.os
          - tail: ${{ dotfiles.path }}/kitty
            head: ~/.config/kitty

  # Install rust toolchain
  - !require [ cargo ]
  - !install
    - name: cargo-edit
      managers: [ cargo ]

  # Install essential packages
  - !install
    - name: git
    - name: bat
    - name: nvim
    - name: gh
    - name: zoxide
    - name: ripgrep
    - name: delta
      aliases: { brew: git-delta, cargo: git-delta }
    - name: pyenv
      managers: [ brew ]

  # Apply symlinks
  - !matrix
      values:
        tail:
          - git/.gitconfig
          - git/.gitignore_global
          - python/.isort.cfg
          - ssh/.ssh_config
        head:
          - ~/.gitconfig
          - ~/.gitignore_global
          - ~/.isort.cfg
          - ~/.ssh/config
      include:
        - !link
          - tail: ${{ dotfiles.path }}/${{ matrix.tail }}
            head: ${{ matrix.head }}

  # User specific configs
  - !case
    - condition: !locale { user: julianth }
      include:
        - !link
          - tail: ${{ dotfiles.path }}/git/.gitconfig.user.julianth
            head: ~/.gitconfig.user
          - tail: ${{ dotfiles.path }}/ssh/.ssh_config.user.julianth
            head: ~/.ssh/config.user
    - include:
        - !link
          - tail: ${{ dotfiles.path }}/git/.gitconfig.user.default
            head: ~/.gitconfig.user
          - tail: ${{ dotfiles.path }}/ssh/.ssh_config.user.default
            head: ~/.ssh/config.user
