---
version: '>=0.7.0, 0.8.0-dev'
build:
  - !repo
      path: ~/dotfiles
      url: https://github.com/jcthomassie/dotfiles.git

  # OS specifics:
  - !case
    - condition: !any
        - !locale { distro: ubuntu }
        - !locale { distro: debian }
      include:
        - !package_manager
            name: apt
            shell_has: dpkg -l ${{ package.alias }}
            shell_install: apt install -y ${{ package.alias }}
            shell_uninstall: apt remove -y ${{ package.alias }}
        - !package_manager
            name: apt-get
            shell_has: dpkg -l ${{ package.alias }}
            shell_install: apt-get install -y ${{ package.alias }}
            shell_uninstall: apt-get remove -y ${{ package.alias }}
    - condition: !locale { distro: fedora }
      include:
        - !package_manager
            name: dnf
            shell_has: dnf list -y installed ${{ package.alias }}
            shell_install: dnf install -y ${{ package.alias }}
            shell_uninstall: dnf remove -y ${{ package.alias }}
    - condition: !locale { platform: bsd }
      include:
        - !package_manager
            name: pkg
            shell_has: pkg info ${{ package.alias }}
            shell_install: pkg install -y ${{ package.alias }}
            shell_uninstall: pkg remove -y ${{ package.alias }}
    - condition: !default
      include:
        - !package_manager
            name: brew
            shell_bootstrap: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            shell_has: brew list ${{ package.alias }}
            shell_install: brew install -y ${{ package.alias }}
            shell_uninstall: brew uninstall -y ${{ package.alias }}

  - !case
    # Ubuntu only
    - condition: !locale { distro: ubuntu }
      include:
        - !package { name: build-essential }
        - !package { name: libffi-dev }
        - !package { name: libssl-dev }
        - !package { name: pkg-config }

  - !case
    # MacOS only
    - condition: !locale { distro: macos }
      include:
        - !link
            target: ${{ repo#dotfiles.path }}/ssh/.ssh_config.os.macos
            source: ~/.ssh/config.os
    # Linux only
    - condition: !locale { platform: linux }
      include:
        - !link
            target: ${{ repo#dotfiles.path }}/ssh/.ssh_config.os.linux
            source: ~/.ssh/config.os

  # Install rust toolchain
  - !package_manager
      name: cargo
      shell_bootstrap: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      shell_has: cargo install --list | grep '^${{ package.alias }} v'
      shell_install: cargo install --locked ${{ package.alias }}
      shell_uninstall: cargo uninstall ${{ package.alias }}
  - !package
      name: cargo-edit
      managers: [ cargo ]

  # Install essential packages
  - !package { name: wezterm }
  - !package { name: zsh }
  - !package { name: eza, managers: [ cargo, brew ] }
  - !package { name: grep }
  - !package { name: curl }
  - !package { name: git }
  - !package { name: bat }
  - !package { name: nvim }
  - !package { name: gh }
  - !package { name: zoxide }
  - !package { name: ripgrep }
  - !package { name: fzf }
  - !package { name: gitui, managers: [ cargo ] }
  - !package { name: direnv }
  - !package
      name: delta
      aliases: { brew: git-delta, cargo: git-delta }
  - !package
      name: yazi-fm
      managers: [ cargo ]
  - !package
      name: yazi-cli
      managers: [ cargo ]

  # Install python toolchain
  - !package_manager
      name: uv
      shell_bootstrap: curl -LsSf https://astral.sh/uv/install.sh | sh

  # Apply symlinks
  - !link
      target: ${{ repo#dotfiles.path }}/zsh/.zshenv
      source: ~/.zshenv
  - !link
      target: ${{ repo#dotfiles.path }}/nvim
      source: ~/.config/nvim
  - !link
      target: ${{ repo#dotfiles.path }}/yazi
      source: ~/.config/yazi
  - !link
      target: ${{ repo#dotfiles.path }}/git/.gitconfig.os.posix
      source: ~/.gitconfig.os
  - !link
      target: ${{ repo#dotfiles.path }}/git/.gitconfig
      source: ~/.gitconfig
  - !link
      target: ${{ repo#dotfiles.path }}/git/.gitignore_global
      source: ~/.gitignore_global
  - !link
      target: ${{ repo#dotfiles.path }}/ssh/.ssh_config
      source: ~/.ssh/config
  - !link
      target: ${{ repo#dotfiles.path }}/claude/CLAUDE.md
      source: ~/.claude/CLAUDE.md
  - !link
      target: ${{ repo#dotfiles.path }}/claude/settings.json
      source: ~/.claude/settings.json
  - !link
      target: ${{ repo#dotfiles.path }}/claude/statusline-command.sh
      source: ~/.claude/statusline-command.sh
  - !link
      target: ${{ repo#dotfiles.path }}/zed/settings.json
      source: ~/.config/zed/settings.json
  - !link
      target: ${{ repo#dotfiles.path }}/wezterm/.wezterm.lua
      source: ~/.wezterm.lua

  # User specific configs
  - !link
      target: ${{ repo#dotfiles.path }}/git/.gitconfig.user.default
      source: ~/.gitconfig.user
  - !link
      target: ${{ repo#dotfiles.path }}/ssh/.ssh_config.user.default
      source: ~/.ssh/config.user
