---
repo:
  local: $HOME/dotfiles
  remote: https://github.com/jcthomassie/dotfiles.git

build:
  # Install ubuntu build requirements
  - case:
    - positive:
        spec:
          distro: ubuntu
        build:
          - install:
            - name: build-essentials
              managers: [ apt ]

  # Bootstrap package managers
  - bootstrap: [ cargo ]
  - case:
    # Windows only
    - positive:
        spec: { platform: windows }
        build:
          - bootstrap: [ choco ]
    # Posix only
    - negative:
        spec: { platform: windows }
        build:
          - bootstrap: [ brew ]
          - install:
            - name: zsh
              managers: [ brew, apt-get ]
            - name: exa
              managers: [ brew, apt, cargo ]
          - link:
            - tail: $YURT_REPO_LOCAL/zsh/.zshenv
              head: $HOME/.zshenv

  # Install essential packages
  - install:
    - name: git
      managers: [ brew, choco ]
    - name: delta
      alias: git-delta
      managers: [ brew, cargo, choco ]
    - name: bat
      managers: [ brew, choco, cargo, apt ]
    - name: vim
      managers: [ brew, choco ]
    - name: gh
      managers: [ brew, choco ]

  # Apply symlinks
  - link:
    - tail: $YURT_REPO_LOCAL/.gitconfig
      head: $HOME/.gitconfig
    - tail: $YURT_REPO_LOCAL/.gitignore_global
      head: $HOME/.gitignore_global
    - tail: $YURT_REPO_LOCAL/.vimrc
      head: $HOME/.vimrc

  # Amazon specifics
  - case:
    - positive:
        spec: { user: thomajl }
        build:
          - link:
            - tail: $YURT_REPO_LOCAL/.gitconfig.local##user.thomajl
              head: $HOME/.gitconfig.local
    - default:
        build:
          - link:
            - tail: $YURT_REPO_LOCAL/.gitconfig.local##default
              head: $HOME/.gitconfig.local
