#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        echo "Setting up OSX"
        # install homebrew if it's missing
        if ! command -v brew >/dev/null 2>&1; then
            echo "Installing homebrew"
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
        brew analytics off
        brew bundle --global
        ;;

    linux*)
        echo "Setting up Linux"
        sudo apt-get update -y
        sudo apt-get install -y zsh git yadm bat
        ;;

    *)
        echo "Setup not configured for $OSTYPE"
        ;;
esac

# Set shell
chsh -s $(which zsh)

# Install submodules
INIT_DIR=$(pwd)
cd $HOME
echo "Initializing submodules"
yadm submodule update --init --recursive
cd $INIT_DIR
