#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        echo "Setting up OSX"
        # install homebrew if it's missing
        if ! command -v brew >/dev/null 2>&1; then
            echo "Installing homebrew"
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
        brew analytics off
        brew bundle --global
        ;;

    *)
        echo "Setup not configured for $OSTYPE"
        ;;
esac

# Install oh-my-zsh
if ! [ "$(ls -A $ZSH)" ]; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

$HOME/bin/update
