---
version: 0.1.0

repo:
  local: ~/dotfiles
  remote: https://github.com/jcthomassie/dotfiles.git

shell: zsh

build:
  # Install ubuntu build requirements
  - case:
    - positive:
        spec:
          distro: ubuntu
        build:
          - install:
            - name: build-essentials
              managers: [ apt ]

  # Bootstrap package managers
  - bootstrap: [ cargo ]
  - case:
    # Windows only
    - positive:
        spec: { platform: windows }
        build:
          - bootstrap: [ choco ]
    # Posix only
    - negative:
        spec: { platform: windows }
        build:
          - bootstrap: [ brew ]
          - install:
            - name: zsh
              managers: [ brew, apt-get ]
            - name: exa
              managers: [ brew, apt, cargo ]
          - link:
            - tail: $YURT_REPO_LOCAL/zsh/.zshenv
              head: ~/.zshenv

  # Install essential packages
  - install:
    - name: git
      managers: [ brew, choco ]
    - name: delta
      alias: git-delta
      managers: [ brew, cargo, choco ]
    - name: bat
      managers: [ brew, choco, cargo, apt ]
    - name: vim
      managers: [ brew, choco ]
    - name: gh
      managers: [ brew, choco ]

  # Apply symlinks
  - link:
    - tail: $YURT_REPO_LOCAL/git/.gitconfig
      head: ~/.gitconfig
    - tail: $YURT_REPO_LOCAL/git/.gitignore_global
      head: ~/.gitignore_global
    - tail: $YURT_REPO_LOCAL/.vimrc
      head: ~/.vimrc
    - tail: $YURT_REPO_LOCAL/python/.flake8
      head: ~/.flake8
    - tail: $YURT_REPO_LOCAL/python/.mypy.ini
      head: ~/.mypy.ini

  # Amazon specifics
  - case:
    - positive:
        spec: { user: thomajl }
        build:
          - link:
            - tail: $YURT_REPO_LOCAL/git/.gitconfig.local##user.thomajl
              head: ~/.gitconfig.local
    - default:
        build:
          - link:
            - tail: $YURT_REPO_LOCAL/git/.gitconfig.local##default
              head: ~/.gitconfig.local
